global:
  resolve_timeout: 5m
route:
  receiver: 'slack-notifications'
  group_by: ['alertname']
receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts'
        send_resolved: true
